/*
Matilda Edlund
Target grade: 5
Some code in this project was generated by the help of chatGPT (though mostly I ask him and then I take the relevant information after I've understood it, I dont copy directly.)
Sources:
leaf icon: emoji
    monstera: <a href="https://www.freepik.com/free-photo/monstera-deliciosa-plant-pot_18097338.htm">Image by rawpixel.com on Freepik</a>
    peace lily: <a href="https://www.vecteezy.com/free-png/peace-lily">Peace Lily PNGs by Vecteezy</a>
    chinese money plant: <a href="https://www.vecteezy.com/free-png/plant">Plant PNGs by Vecteezy</a>
    instagram icon: <a target="_blank" href="https://icons8.com/icon/32309/instagram">Instagram</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>
    facebook icon: <a target="_blank" href="https://icons8.com/icon/WI60cLQ7XN0Q/facebook">Facebook</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>
    polka dot plant: https://www.google.com/url?sa=i&url=https%3A%2F%2Fplantaddicts.com%2Fhippo-white-polka-dot-plant%3Fsrsltid%3DAfmBOooaNQ9ZE-QIdANDoI8dZM_pr2jnx75DTIzhVFZ6Q5go_Kky5QGK&psig=AOvVaw0OxJW3aKzUXILCTbg0t26Y&ust=1759317571871000&source=images&cd=vfe&opi=89978449&ved=0CBUQjRxqFwoTCMDGjvCugJADFQAAAAAdAAAAABAu
    spider plant: <a href="https://www.vecteezy.com/free-png/spider-plant">Spider Plant PNGs by Vecteezy</a>
    coleus: <a href="https://www.vecteezy.com/free-png/vibrant">Vibrant PNGs by Vecteezy</a>
    cactus: <a href="https://www.vecteezy.com/free-png/cactus">Cactus PNGs by Vecteezy</a>
    aloe vera: <a href="https://www.vecteezy.com/free-png/aloe-vera">Aloe Vera PNGs by Vecteezy</a>
    leaf fig: <a href="https://www.vecteezy.com/free-png/potted">Potted PNGs by Vecteezy</a>
    snake plant: <a href="https://www.vecteezy.com/free-png/snake-plant">Snake Plant PNGs by Vecteezy</a>
    peperomia: <a href='https://pngtree.com/freepng/watermelon-peperomia-plant-in-white-ceramic-pot_21456265.html'>png image from pngtree.com/</a>
    zz plant: <a href="https://www.vecteezy.com/free-png/plant">Plant PNGs by Vecteezy</a>
    pothos: <a href="https://www.vecteezy.com/free-png/leaf">Leaf PNGs by Vecteezy</a>
    jade plant: <a href="https://www.vecteezy.com/free-png/jade-plant">Jade Plant PNGs by Vecteezy</a>
    rubber plant: <a href="https://www.vecteezy.com/free-png/rubber-plant">Rubber Plant PNGs by Vecteezy</a>
    zebra plant: <a href="https://www.vecteezy.com/free-png/leaf">Leaf PNGs by Vecteezy</a>
    air plant: <a href="https://www.vecteezy.com/free-png/air-plant">Air Plant PNGs by Vecteezy</a>
    philodendron: <a href="https://www.vecteezy.com/free-png/philodendron">Philodendron PNGs by Vecteezy</a>
    parlor palm: <a href="https://www.vecteezy.com/free-png/plant">Plant PNGs by Vecteezy</a>
    chinese evergreen: <a href="https://www.vecteezy.com/free-png/transparent-background">Transparent Background PNGs by Vecteezy</a>
    alocasia: <a href="https://www.vecteezy.com/free-png/plant">Plant PNGs by Vecteezy</a>
    Photo by <a href="https://unsplash.com/@eddybllrd?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Eddy Billard</a> on <a href="https://unsplash.com/photos/green-taro-plants-kHLtOFkjNZs?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>

*/


const express=require('express') // read the express library
const {engine} = require('express-handlebars') // load the handlebars package for express
const sqlite3=require('sqlite3')
const bcrypt=require('bcrypt')
const session=require('express-session')
const connectSqlite3=require('connect-sqlite3')

const port=8000 // define the port
const app=express() // create the express application

app.engine('handlebars', engine()) // initialize the engine to be handlebars
app.set('view engine', 'handlebars') // set handlebars as the view engine
app.set('views', './views') // define the views directory to be './views' this is to avoid writing __dirname

//processing forms sent using the form method
app.use(express.urlencoded({ extended: true })); // for processing forms
const dbFile='my-project-data.sqlite3.db'
db=new sqlite3.Database(dbFile)
db.run("PRAGMA foreign_keys = ON");
db.run("PRAGMA busy_timeout = 5000");

const SQLiteStore = connectSqlite3(session) // store sessions in database

app.use(session({ // initialize session
    store: new SQLiteStore({db: "session-db.db"}),
    "saveUninitialized" : false,
    "resave" : false,
    "secret" : "This123Is@Another#456GreatSecret678%Sentence"
}))

app.use((req, res, next) => { // make sessions available on any page of the application
    res.locals.session = req.session
    next()
})

app.use(express.static(__dirname + '/public')); // this is to get style and images of web page, anything from
//  /public will be available from root URL, so no need to write /public/img etc

app.get('/', (req, res) => {   // define the default route '/'
    //res.send('Hello World!')
    res.render('home', {bodyClass: 'home-page'})
})

app.get('/about', (req, res) => {   
    res.render('about', {bodyClass: 'about-page'})
})

app.get('/contact', (req, res) => {   
    res.render('contact', {bodyClass: 'contact-page'})
})

app.get('/catalog', (req, res) => {   
    db.get("SELECT COUNT(*) AS count FROM products", (error, row) =>{ // row is the data received from query
        if(error){
            console.error(error.message)
            const model = {error: "Error counting products from database."}
            res.render()
        } else {
            const limit = 8;
            const totalProducts = row.count
            const totalPages=Math.ceil(totalProducts/limit) // rounds UP
            let currentPage=parseInt(req.query.page) || 1 //gets the query string page, if it returns null, the page is 1
            console.log(`---> Current page: ${currentPage}`)
            if(currentPage > totalPages) currentPage = totalPages
            if(currentPage < 1) currentPage = 1
            pages = []
            for(i = 1; i <= totalPages; i++){
                pages.push(i)
            }

            const offset=limit*(currentPage-1) //removes products from earlier pages
            console.log(`---> OFFSET for SQL LIMIT clause: ${offset}`)
            db.all("SELECT * FROM products LIMIT ? OFFSET ?", [limit, offset], (error, listOfProducts) => {
                if(error){
                    console.error(error.message)
                    const model = {error: "Error retrieving products from the database"} // this is so the user sees a pretty error message instead of site just crashing
                    res.render(products, model)
                } else {
                    console.log(`---> Retrieved ${listOfProducts.length} products from the database.`)
                    console.log(`---> Products: ${JSON.stringify(listOfProducts)}`)
                    const model={
                        products : listOfProducts, 
                        bodyClass: 'catalog-page', 
                        totalPages: totalPages, 
                        currentPage : currentPage,
                        prevPage : currentPage - 1, 
                        nextPage : currentPage + 1,
                        pages : pages,
                        hasPrevPage : currentPage > 1,
                        hasNextPage : currentPage < totalPages
                    }
                    res.render('catalog', model)
                }
             })
        }
    })  
})

app.get('/catalog/new', (req, res) => {
    if(req.session.isAdmin){
        res.render('form-product')
    } else {
        model = {error: "You must be logged in as admin to create a new product"}
        res.render('login', model)
    }
})

app.post('/catalog/new', (req, res) => {
    console.log(`Here comes the data received from the form on the client: ${JSON.stringify(req.body)}`)
    const {pname, pdesc, price, url} = req.body
    if(req.session.isAdmin){
        db.run("INSERT INTO products (pname, pdesc, price, url) VALUES (?, ?, ?, ?)", [pname, pdesc, price, url], (error) => {
            if(error){
                console.error(error.message)
                const model = {error: "Error inserting the new product into the database."}
                res.redirect('/', model)
            } else {
                console.log('New product created!')
                res.redirect('/catalog')
            }
        })
    } else {
        const model = {error: "You must be logged in as admin to create a new product."}
        res.render('login', model)
    }
})

app.get('/catalog/:prodid', (req, res) => {
    let productId = req.params.prodid // this comes from URL
    db.get('SELECT * FROM products WHERE pid = ?', [productId], (error, theProduct) => {
        if(error){
            console.error(error.message)
            const model = {error: "Error retrieving product from the database"} 
            res.render('product', model)
        } else {
            //console.log(`---> Retrieved product: ${JSON.stringify(theProduct)} from the database.`)
            const model = {product: theProduct}
            res.render('product', model)
        }
    })
})

app.get('/catalog/modify/:prodid', (req, res) => {
    let productId = req.params.prodid
    if(req.session.isAdmin){
        db.get("SELECT * FROM products WHERE pid = ?", [productId], (error, theProduct) => {
            if(error){
                console.error(error.message)
                const model = {error: "Error retrieving product from the database"} 
                res.render('product', model)
            } else {
                const model = {product: theProduct}
                res.render('form-product', model)
            }
        })
    } else {
        const model = {error: "You must be logged in as admin to edit a product."}
        res.render('login', model)
    }
})

app.post('/catalog/modify/:prodid', (req, res) => {
    let productId = req.params.prodid
    console.log(`Here comes the data received from the form on the client: ${JSON.stringify(req.body)}`)
    const {pname, pdesc, price, url} = req.body
    if(req.session.isAdmin){
        db.run("UPDATE products SET pname = ?, pdesc = ?, price = ?, url = ? WHERE pid = ?", [pname, pdesc, price, url, productId], (error) => {
            if(error){
                console.error(error.message)
                const model = {error: "Error updating the product into the database."}
                res.redirect('/', model)
            } else {
                console.log('Product has been modified!')
                res.redirect('/catalog')
            }
        })
    } else {
        const model = {error: "You must be logged in as admin to update a new product."}
        res.render('login', model)
    }
})

app.post('/catalog/delete/:prodid', (req, res) => {
    let productId = req.params.prodid

    if(req.session.isAdmin){
        db.serialize(() => {
            db.run("DELETE FROM products WHERE pid = ?", [productId], (error) => {
                if(error){
                    console.error(error.message)
                    console.log("Error deleting the product from the database.")
                    res.redirect('/')
                } else {
                    console.log("The product was deleted")
                    res.redirect('/catalog')
                }
            })
        })
    } else {
        const model = {error: "You must be logged in as admin to delete a product"}
        res.render('login', model)
    }
})

app.get('/login', (req, res) => {
    const model = {bodyClass: 'login-page'}
    res.render('login', model)
})

app.post('/login', (req, res) => {
    const username = req.body.un;
    const password = req.body.pw;
    db.get('SELECT * FROM users WHERE username = ?', [username], (err, row) => {
        if(err){
            console.error(err.message)
            model= {error: "Error retrieving user from database."}
            res.render('login', model)
        } if(!row){
            console.log('Wrong username!')
            model= {error: "Wrong username! Please try again."}
            res.render('login', model)
        }
        else {
            bcrypt.compare(password, row.password, (err, result) => {
                if(err){
                    console.log('Error in password comparison.')
                    model= {error: "Error in password comparison."}
                    res.render('login', model)
                }
                if(result){
                    req.session.isLoggedIn=true
                    req.session.un=req.body.un
                    req.session.isAdmin=row.isAdmin==='yes'
                    req.session.uid=row.uid
                    console.log('--> SESSION INFORMATION: ', JSON.stringify(req.session))
                    res.render('profile')
                } else {
                    console.log('Wrong password')
                    model = {error: "Wrong password! Please try again."}
                    res.render('login', model)
                }
            })
        }
    })
})

app.get('/login/new', (req, res) => {
    res.render('form-user', {bodyClass: "login-page"})
})

app.post('/login/new', async (req, res) => {
    console.log(`Here comes the data received from the form on the client: ${JSON.stringify(req.body)}`)
    const {un, pw, pw2} = req.body
    if(pw === pw2){
        const password = await hashPassword(pw, 12)
        db.run("INSERT INTO users (username, password, isAdmin) VALUES (?, ?, ?)", [un, password, 'no'], (error) => {
            if(error){
                console.error(error.message)
                const model = {error: "Error inserting the new user into the database."}
                res.render('home', model)
            } else {
                console.log('New user created!')
                res.redirect('/login')
            }
        })
    } else {
        console.log("Passwords don't match")
        const model = {error: "Passwords do not match."}
        res.render('login', model)
    }
    
})

app.get('/profile', (req, res) => {
    res.render('profile')
})

app.get('/profile/users', (req, res) => {
    if(req.session.isAdmin){
        db.all("SELECT * FROM users", (error, listOfUsers) => {
            if(error){
                console.error(error.message)
                const model = {error: "Error retrieving users from the database."}
                res.render('profile', model)
            } else {
                listOfUsers.forEach(user => {
                    user.isAdmin = user.isAdmin === "yes"
                })
                console.log(`---> Retrieved ${listOfUsers.length} users from the database.`)
                console.log(`---> Users: ${JSON.stringify(listOfUsers)}`)
                const model = {user : listOfUsers}
                res.render('users', model)
            }
    })
    } else {
        const model = {error: "You must be logged in as admin to access users"}
        res.render('profile', model)
    }
    
})

app.post('/profile/users', (req, res) => {
    console.log(`Here comes the data received from the form on the client: ${JSON.stringify(req.body)}`)
    if(req.session.isAdmin){
        db.all("SELECT uid FROM users", (error, users) => {
            if(error){
                console.error(error.message)
                const model = {error: "Error receiving users from database."}
                res.render('home', model)
            } else {
                users.forEach(user => {
                    const isAdmin = req.body[user.uid] ? "yes" : "no"

                    db.run("UPDATE users SET isAdmin = ? WHERE uid = ?", [isAdmin, user.uid], (error) => {
                        if(error){
                            console.error(error.message)
                            const model = {error: "Error updating users to database."}
                            res.render('home', model)
                        } else {
                            console.log(`User ${user.uid} has been updated`)
                        }
                    })
                })
                res.redirect('/profile')
            }
        })
    } else {
        const model = {Error: "You need to log in as admin to update users!"}
        res.render('home', model)
    }
})

app.post('/profile/users/delete/:userid', (req, res) => {
    let userId = req.params.userid

    if(req.session.isAdmin){
        db.serialize(() => {
            db.run("DELETE FROM users WHERE uid = ?", [userId], (error) => {
                if(error){
                    console.error(error.message)
                    console.log("Error deleting the user from the database.")
                    res.render('profile')
                } else {
                    console.log("The user was deleted")
                    res.redirect('/profile/users')
                }
            })
        })
    } else {
        const model = {error: "You must be logged in as admin to delete a user"}
        res.render('login', model)
    }
})

app.get('/profile/orders', (req, res) => {
    let sql = 'SELECT orders.*,users.username, products.pid, products.pname, products.price, products.url, orderHasProducts.quantity FROM products INNER JOIN orderHasProducts ON products.pid=orderHasProducts.pid INNER JOIN orders ON orderHasProducts.oid=orders.oid INNER JOIN users ON orders.uid=users.uid'
    let params = []
    if(!req.session.isAdmin){
        sql += ' WHERE orders.uid = ? ORDER BY orders.oid DESC'
        params = [req.session.uid]
    } else {
        sql += ' ORDER BY orders.oid DESC'
    }

    db.all(sql, params, (error, rows) => {
        if(error){
            console.error(error.message)
            const model = {error: "Error retrieving the data from database"}
            res.render('profile', model)
        } else {
            const ordersMap = new Map();
            rows.forEach(row => {
                const oid = row.oid;
                if(!ordersMap.has(oid)){
                    ordersMap.set(oid, {
                        oid: row.oid,
                        username: row.username,
                        date: row.date,
                        status: row.status,
                        products: []
                    })
                }
                ordersMap.get(oid).products.push({
                    url: row.url,
                    pname: row.pname,
                    price: row.price,
                    quantity: row.quantity
                })
            })
            const orders = Array.from(ordersMap.values())
            console.log(`---> Retrieved ${rows.length} rows from the database.`)
            console.log(JSON.stringify(orders, null, 2))
            res.render('orders', {orders})
        }
    })
})

app.get('/logout', (req, res) => {
    req.session.destroy( (err) => { //destroy the session when logging out
        if(err){
            console.log("Error while destroying session: ", err)
            res.redirect('/')
        } else {
            console.log("Logged out")
            res.redirect('/')
        }
    })
})

app.use((req, res) => {
    res.status(404).render('404.handlebars')
})

app.use((error, req, res, next) => {
    console.error(error.stack)
    res.status(500).render('500')
})

app.listen(port, () => {  // listen on the port
    //initTableProducts(db)
    //initTableOrders(db)
    //initTableUsers(db)
    //initTableOrderHasProducts(db)
    //hashPassword("wdf#2025", 12) //12 is standard saltrounds
    //storePassword("$2b$12$IdXP55GgrUnk5s0DQdqL6u18A3YiSsFmfaIETE/NvhkjqwDdYHrv2", 2)
    //storeDescription("The Monstera is a tropical houseplant known for its large, glossy leaves that develop natural splits as it grows. It’s easy to care for and adds a bold, lush look to any room.", 1);
    //updateAdmin("no", 4)
    console.log('Server up and running on http://localhost:${port}...')
})

//initializing tables functions
function initTableUsers(mydb){
    const users=[
        {"id":"1", "username":"matildaedlund", "password":""},
        {"id":"2", "username":"sandragren", "password":""},
        {"id":"3", "username":"benjaminpirmandi", "password":""},
        {"id":"4", "username":"emiliaedlund", "password":""},
        {"id":"5", "username":"kylavisagie", "password":""}        
    ]

    db.run("CREATE TABLE IF NOT EXISTS users (uid INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT NOT NULL, password TEXT)", (error) => {
        if(error){
            console.log("ERROR: ", error) // display error in the terminal
        } else {
            console.log("---> Table Users created!")

            users.forEach( (u) => {
                db.run("INSERT INTO users (uid, username, password) VALUES (?, ?, ?)",
                [u.id, u.username, u.password], (error) => {
                    if(error){
                        console.log("ERROR: ", error)
                    } else {
                        console.log("Line added inte the users table!")
                    }
                })
            })
        }
    })
}

function initTableProducts(mydb){
    const products=[
        {"id":"1", "name":"Monstera", "description":"", "price":"249", "url":"/img/monstera.jpg"},
        {"id":"2", "name":"Peace Lily", "description":"", "price":"149", "url":"/img/peace-lily.png"},
        {"id":"3", "name":"Chinese Money Plant", "description":"", "price":"99", "url":"/img/money-plant.png"},
        {"id":"4", "name":"Polka dot Plant", "description":"", "price":"44.90", "url":"/img/polka-dot.jpg"},
        {"id":"5", "name":"Spider Plant", "description":"", "price":"79.90", "url":"/img/spider-plant.png"},
        {"id":"6", "name":"Peperomia", "description":"", "price":"89.90", "url":"/img/peperomia.jpg"},
        {"id":"7", "name":"Aloe Vera", "description":"", "price":"99", "url":"/img/aloe-vera.png"},
        {"id":"8", "name":"Cactus", "description":"", "price":"59.90", "url":"/img/cactus.png"},
        {"id":"9", "name":"Coleus", "description":"", "price":"69.90", "url":"/img/coleus.png"},
        {"id":"10", "name":"Jade Plant", "description":"", "price":"99", "url":"/img/jade-plant.png"},
        {"id":"11", "name":"Leaf Fig", "description":"", "price":"149", "url":"/img/leaf-fig.png"},
        {"id":"12", "name":"Pothos", "description":"", "price":"199", "url":"/img/pothos.png"},
        {"id":"13", "name":"Rubber Plant", "description":"", "price":"129", "url":"/img/rubber-plant.png"},
        {"id":"14", "name":"Snake Plant", "description":"", "price":"179", "url":"/img/snake-plant.png"},
        {"id":"15", "name":"Zz Plant", "description":"", "price":"199", "url":"/img/zz-plant.png"},
        {"id":"16", "name":"Alocasia", "description":"", "price":"299", "url":"/img/alocasia.png"},
        {"id":"17", "name":"Chinese Evergreen", "description":"", "price":"249", "url":"/img/chinese-evergreen.png"},
        {"id":"18", "name":"Parlor Palm", "description":"", "price":"119.70", "url":"/img/parlor-palm.png"},
        {"id":"19", "name":"Philodendron", "description":"", "price":"199", "url":"/img/philodendron.png"},
    ]

    db.run("CREATE TABLE IF NOT EXISTS products (pid INTEGER PRIMARY KEY AUTOINCREMENT, pname TEXT NOT NULL, pdesc TEXT, price REAL NOT NULL, url TEXT NOT NULL)", (error) => {
        if(error){
            console.log("ERROR: ", error) // display error in the terminal
        } else {
            console.log("---> Table Products created!")

            products.forEach( (p) => {
                db.run("INSERT INTO products (pid, pname, pdesc, price, url) VALUES (?, ?, ?, ?, ?)",
                [p.id, p.name, p.description, p.price, p.url], (error) => {
                    if(error){
                        console.log("ERROR: ", error)
                    } else {
                        console.log("Line added into the products table!")
                    }
                })
            }) 
           /*moreProducts.forEach( (p) => {
            db.run("DELETE FROM products")
           })*/
        }
    })
}

function initTableOrderHasProducts(mydb){
    const orderHasProducts=[
        {"oid":"1", "pid":"1", "quantity":"1"},
        {"oid":"1", "pid":"2", "quantity":"1"},
        {"oid":"1", "pid":"4", "quantity":"2"},
        {"oid":"2", "pid":"3", "quantity":"1"},
        {"oid":"2", "pid":"5", "quantity":"1"},
        {"oid":"3", "pid":"1", "quantity":"1"},
        {"oid":"4", "pid":"2", "quantity":"2"},
        {"oid":"4", "pid":"3", "quantity":"1"},
        {"oid":"5", "pid":"5", "quantity":"2"},
        {"oid":"6", "pid":"10", "quantity":"1"},
        {"oid":"6", "pid":"9", "quantity":"2"},
        {"oid":"7", "pid":"15", "quantity":"2"},
        {"oid":"7", "pid":"11", "quantity":"1"}
    ]

     db.run("CREATE TABLE IF NOT EXISTS orderHasProducts (oid INTEGER NOT NULL, pid INTEGER NOT NULL, quantity INTEGER NOT NULL CHECK (quantity > 0), PRIMARY KEY (oid, pid), FOREIGN KEY (oid) REFERENCES orders(oid), FOREIGN KEY (pid) REFERENCES products(pid))", (error) => {
        if(error){
            console.log("ERROR: ", error) // display error in the terminal
        } else {
            console.log("---> Table orderHasProducts created!")

            orderHasProducts.forEach( (up) => {
                db.run("INSERT INTO orderHasProducts (oid, pid, quantity) VALUES (?, ?, ?)",
                [up.oid, up.pid, up.quantity], (error) => {
                    if(error){
                        console.log("ERROR: ", error)
                    } else {
                        console.log("Line added into the orderHasProducts table!")
                    }
                })
            })
        }
    })
}

function initTableOrders(mydb){
    const orders=[
        {"id":"1", "uid":"1", "status":"pending"},
        {"id":"2", "uid":"2", "status":"pending"},
        {"id":"3", "uid":"3", "status":"pending"},
        {"id":"4", "uid":"4", "status":"pending"},
        {"id":"5", "uid":"5", "status":"pending"},
        {"uid":"3", "status":"pending"},
        {"uid":"6", "status":"pending"}
    ]

    db.run("CREATE TABLE IF NOT EXISTS orders (oid INTEGER PRIMARY KEY AUTOINCREMENT, uid INTEGER NOT NULL, status TEXT NOT NULL, date TEXT DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (uid) REFERENCES users(uid))", (error) => {
        if(error){
            console.log("ERROR: ", error) // display error in the terminal
        } else {
            console.log("---> Table Orders created!")

            orders.forEach( (u) => {
                db.run("INSERT INTO orders (oid, uid, status) VALUES (?, ?, ?)",
                [u.id, u.uid, u.status], (error) => {
                    if(error){
                        console.log("ERROR: ", error)
                    } else {
                        console.log("Line added inte the orders table!")
                    }
                })
            })
        }
    })

}

// other functions
function hashPassword(pw, saltRounds){  //saltrounds is how many times the password will be hashed (higher=more security but slower)
    return new Promise((resolve, reject) => {
        bcrypt.hash(pw, saltRounds, function(err,hash){ //some of this code is from chatGPT
        if(err){
            console.log('--> Error hashing password')
            reject(err)
        } else {
            console.log(`--> Hashed password: ${hash}`)
            resolve(hash)
        }
    })  
    })
}

function storePassword(pw, id){
    db.run("UPDATE users SET password = ? WHERE uid = ?", [pw, id], (err) => {
        if (err){
            console.log('error storing password.')
        } else {
            console.log('stored password successfully!')
        }
    })
}

function storeDescription(desc, id){
    db.run("UPDATE products SET pdesc = ? WHERE pid = ?", [desc, id], (err) =>{
        if(err){
            console.error(err.message)
        } else {
            console.log('stored description successfully!')
        }
    })
}

function updateAdmin(admin, id){
    db.run("UPDATE users SET isAdmin = ? WHERE uid = ?", [admin, id], (err) =>{
        if(err){
            console.error(err.message)
        } else {
            console.log('updated admin successfully!')
        }
    })
}


// DATABASE QUERIES
//db.run("ALTER TABLE users ADD COLUMN isAdmin TEXT") // to add a column to a table

// drops table
/*db.run("DROP TABLE IF EXISTS products", (error) => {
  if (error) {
    console.log("Error dropping table:", error);
  } else {
    console.log("✅ Table 'products' dropped successfully!");
  }
});*/

//inserts into products table
//db.run("INSERT INTO products (pname, pdesc, price, url) VALUES ('Peperomia', '', 89.90, 'img/peperomia.jpg')")
//db.run("INSERT INTO users (username, password, isAdmin) VALUES ('admin', '$2b$12$TswiTs.CS3DKuXiNzBSXpOhz5dgH/6NJqmKoQlecPnkDJZVoGf4h.', 'yes')")

//inserts password into user
//db.run("UPDATE users SET password = ? WHERE uid = ?", [benjiPassword, 3])
//db.run("UPDATE users SET isAdmin = ? WHERE uid IN (?, ?, ?, ?)", ['no', 2, 4, 5, 6])

//deletes from products table
/*db.run("DELETE FROM users WHERE uid IN (?, ?, ?, ?, ?, ?, ?, ?)", [8, 9, 10, 11, 12, 13, 14, 15], (err) => {
  if (err) {
    console.log("Error deleting products:", err);
  } else {
    console.log("Products deleted successfully!");
  }
});*/  // ? is a placeholder, deletes in a safe way

// db.run("UPDATE products SET url = ? WHERE pid = ?", ["/img/peperomia.png", 6]) // updates entry in table








